# Generated by Django 4.2.7 on 2024-07-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=255)),
                ('insurer_ref', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('client_ref', models.CharField(max_length=255)),
                ('claimant', models.CharField(max_length=255)),
                ('insured', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('1', 'WC'), ('2', 'CTP')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Claimant'), (2, 'Insured'), (3, 'Employer Contact'), (4, 'Witness'), (5, 'Client Contact'), (6, 'Service'), (7, 'Other')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
