# Generated by Django 4.2.7 on 2024-08-01 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Case.case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Claimant', 'Claimant'), ('Insured', 'Insured'), ('Employer_Contact', 'Employer Contact'), ('Witness', 'Witness'), ('Client_Contact', 'Client Contact'), ('Other', 'Other')], max_length=100),
        ),
    ]
