# Generated by Django 4.2.7 on 2024-08-02 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_emailtemplate_contact_case_alter_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Case.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.CharField(choices=[('Procare', 'Procare'), ('Worksite', 'Worksite')], max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='insurer',
            field=models.CharField(choices=[('EML', 'EML'), ('Allianz', 'Allianz'), ('Suncorp', 'Suncorp')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='Case.case'),
        ),
    ]
