# Generated by Django 4.2.7 on 2024-08-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0004_note_contact_alter_case_client_alter_case_insurer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='created_at',
        ),
    ]
