# Generated by Django 4.2.7 on 2024-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0005_rename_date_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='insurer',
            field=models.CharField(choices=[('EML', 'EML'), ('Allianz', 'Allianz'), ('Suncorp', 'Suncorp'), ('GIO', 'GIO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
