# Generated by Django 4.2.4 on 2023-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email_address_id', models.CharField(max_length=250)),
                ('email_from_name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
